myblog/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^index/$',views.index),
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)/$', views.edit_page, name='edit_page'),
    url(r'^edit/action$', views.edit_action, name='edit_action'),
]

myblog/blog2/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^index/$',views.index),
]

myblog/myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
#import blog.views as bv;

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     url(r'^index/', bv.index),
# ]
urlpatterns=[
    url(r'^admin/',admin.site.urls),
    url(r'^blog/',include('blog.urls', namespace='blog')),
    url(r'^blog2/',include('blog2.urls')),
]

myblog/blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    tilte=models.CharField(max_length=32,default="title")
    content=models.TextField(null=True)
    pub_time=models.DateTimeField(null=True)

    def __str__(self):
        return self.tilte

myblog/blog2/models.py
from django.db import models

# Create your models here.

myblog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.

# def index(request):
#     #return  HttpResponse("hello,world!")
#     return  render(request,'blog/index.html',{'cwm':'chenwangming','age':28})

# def index(request):
#     article=models.Article.objects.get(pk=1)
#     return render(request,'blog/index.html',{'article':article})

def index(request):
    articles=models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})


def article_page(request,article_id):
    article=models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{"article":article})

def edit_page(requset,article_id):
    if(article_id=='0'):
        return  render(requset,'blog/edit_page.html')
    article=models.Article.objects.get(pk=article_id)
    return render(requset,'blog/edit_page.html',{'article':article})



def edit_action(request):
    title=request.POST.get('title','Title')
    content =request.POST.get('content','neirong')
    article_id=request.POST.get('id','0')
    if(article_id=='0'):
        models.Article.objects.create(tilte=title,content=content)
        articles=models.Article.objects.all()
        return render(request,'blog/index.html',{'articles':articles})
    article=models.Article.objects.get(pk=article_id)
    article.tilte=title
    article.content=content
    article.save()
    return render(request,'blog/article_page.html',{'article':article})

myblog/blog2/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    #return  HttpResponse("hello,world!")
    return  render(request,'blog2/index.html',{'cwm2':'chenwangming2','age':228})

myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article</title>
</head>
<body>
<h2>{{article.tilte}}</h2>
<br>
<h4>
    {{ article.content }}
</h4>
<a href="{% url 'blog:edit_page' article.id%}">编辑页面</a>
</body>
</html>

myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章编辑</title>
</head>
<body>

<div>
    <form action="{% url 'blog:edit_action' %}" method="post">
        {% csrf_token %}
        <!--{% if article %}-->
        <!--<input type="hidden" name="id" value="{{article.id}}">-->
        <!--<label>title</label>-->
        <!--<br>-->
        <!--<input type="text" id="title" name="title" value="{{article.tilte }}">-->
        <!--<br>-->

        <!--<label>content</label>-->
        <!--<br>-->
        <!--<input type="text" name="content" id="content" value="{{article.content }}">-->
        <!--<br>-->
        <!--{% else %}-->
         <!--<input type="hidden" name="id" value="0">-->
         <!--<label>title</label>-->
        <!--<br>-->
        <!--<input type="text" id="title" name="title">-->
        <!--<br>-->

        <!--<label>content</label>-->
        <!--<br>-->
        <!--<input type="text" name="content" id="content">-->
        <!--<br>-->
        <!--{% endif %}-->


        <input type="hidden" name="id" value="{{article.id|default:'0'}}">
        <label>title</label>
        <br>
        <input type="text" id="title" name="title" value="{{article.tilte }}">
        <br>

        <label>content</label>
        <br>
        <input type="text" name="content" id="content" value="{{article.content }}">
        <br>

        <input type="submit"  value="提交">
    </form>
</div>
</body>
</html>

myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>
    您好，我叫陈王明！ 英文名：chenwangming
</h2>
<!--<p>-->
    <!--{{article.tilte}}-->
<!--</p>-->
<!--<p>-->
    <!--{{article.content}}-->
<!--</p>-->
<h2><a href="{% url 'blog:edit_page' 0 %}">新文章</a></h2>
{% for article in articles %}
<a href="{% url 'blog:article_page' article.id %}"> {{article.tilte }}</a>
<br/>
{% endfor %}


</body>
</html>

myblog/blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>
    您好，我叫陈王明！ 英文名：{{ cwm2 }}
</h2>

<p>{{age}}</p>
</body>
</html>